  name: ElmTest
  on:
    push:
      branches:
        - master
        - develop
  jobs:
    test:

      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: npm install
          run: npm install --dev

        - name: genelate elm-spa files
          run: npm run generate

        - name: Run test
          run: npm test
